/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.sql.ResultSet;

import javax.swing.JOptionPane;


class coso implements Serializable{
    public String basededato;
    public String usuario;
    public String password;
    public String instancia;
    public String puerto;
    private static final long serialVersionUID = 1L;
};

/**
 *
 * @author walth
 */
public class GUIConexion extends javax.swing.JFrame {
    


    /**
     * Creates new form GUIConexion
     */
    public GUIConexion() {
        initComponents();
        this.setLocationRelativeTo(this);
        File file = new File("./coso.bin");
        if(file.exists()){
            try{
                FileInputStream fis = new FileInputStream(file);
                ObjectInputStream ois = new ObjectInputStream(fis);
                coso origen = (coso)ois.readObject();
                coso destino = (coso)ois.readObject();
                ois.close();
                fis.close();
                TF_IntanciaOrigen.setText(origen.instancia);
                TF_NombreOrigen.setText(origen.basededato);
                TF_PuertoOrigen.setText(origen.puerto);
                TF_UsuarioOrigen.setText(origen.usuario);
                TF_PasswordOrigen.setText(origen.password);
                TF_IntanciaDestino.setText(destino.instancia);
                TF_NombreDestino.setText(destino.basededato);
                TF_PuertoDestino.setText(destino.puerto);
                TF_UsuarioDestino.setText(destino.usuario);
                TF_PasswordDestino.setText(destino.password);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBaseDestino = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TF_UsuarioDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TF_PasswordDestino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BT_ProbarDestino = new javax.swing.JButton();
        TF_IntanciaDestino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_NombreDestino = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_PuertoDestino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JPBaseOrigen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_IntanciaOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_NombreOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_PuertoOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_UsuarioOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_PasswordOrigen = new javax.swing.JTextField();
        BT_ProbarOrigen = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        JPBaseDestino.setBackground(new java.awt.Color(204, 204, 204));
        JPBaseDestino.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel6.setText("Usuario:");

        jLabel7.setText("Contraseña:");

        jLabel8.setText("Instancia:");

        BT_ProbarDestino.setText("Probar");
        BT_ProbarDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_ProbarDestinoMousePressed(evt);
            }
        });

        jLabel9.setText("Nombre:");

        jLabel10.setText("Puerto:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Base De Datos Destino");

        javax.swing.GroupLayout JPBaseDestinoLayout = new javax.swing.GroupLayout(JPBaseDestino);
        JPBaseDestino.setLayout(JPBaseDestinoLayout);
        JPBaseDestinoLayout.setHorizontalGroup(
            JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBaseDestinoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPBaseDestinoLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_IntanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPBaseDestinoLayout.createSequentialGroup()
                                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_NombreDestino)
                                    .addComponent(TF_PuertoDestino)))
                            .addGroup(JPBaseDestinoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TF_UsuarioDestino))
                            .addGroup(JPBaseDestinoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_PasswordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBaseDestinoLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_ProbarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBaseDestinoLayout.setVerticalGroup(
            JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBaseDestinoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_IntanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_NombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TF_PuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_UsuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(JPBaseDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TF_PasswordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BT_ProbarDestino)
                .addGap(17, 17, 17))
        );

        JPBaseOrigen.setBackground(new java.awt.Color(204, 204, 255));
        JPBaseOrigen.setForeground(new java.awt.Color(255, 204, 255));
        JPBaseOrigen.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel1.setText("Instancia:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Puerto:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Contraseña:");

        BT_ProbarOrigen.setText("Probar");
        BT_ProbarOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_ProbarOrigenMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Base De Datos Origen");

        javax.swing.GroupLayout JPBaseOrigenLayout = new javax.swing.GroupLayout(JPBaseOrigen);
        JPBaseOrigen.setLayout(JPBaseOrigenLayout);
        JPBaseOrigenLayout.setHorizontalGroup(
            JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_IntanciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                                    .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TF_NombreOrigen)
                                        .addComponent(TF_PuertoOrigen)))
                                .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_PasswordOrigen))
                                .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TF_UsuarioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBaseOrigenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BT_ProbarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))))
                    .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        JPBaseOrigenLayout.setVerticalGroup(
            JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBaseOrigenLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_IntanciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_NombreOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_PuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_UsuarioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(JPBaseOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_PasswordOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_ProbarOrigen)
                .addGap(23, 23, 23))
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        B_Guardar.setBackground(new java.awt.Color(255, 255, 0));
        B_Guardar.setForeground(new java.awt.Color(0, 0, 0));
        B_Guardar.setText("Guardar");
        B_Guardar.setOpaque(false);
        B_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B_GuardarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(B_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBaseOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addComponent(JPBaseDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPBaseOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBaseDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ProbarOrigenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ProbarOrigenMousePressed
        if(!BT_ProbarOrigen.isEnabled())
            return;
        String nombre = TF_NombreOrigen.getText();
        String instancia = TF_IntanciaOrigen.getText();
        String puerto = TF_PuertoOrigen.getText();
        String usuario = TF_UsuarioOrigen.getText();
        String password = TF_PasswordOrigen.getText();
        Conexion conexion = new Conexion(nombre, usuario, password, instancia, puerto);
        try{
            conexion.Conectar();
            GUIReplicacion.origen = conexion;
            JOptionPane.showMessageDialog(null, "Conexion exitosa");
            BT_ProbarOrigen.setEnabled(false);
            TF_IntanciaOrigen.setEnabled(false);
            TF_NombreOrigen.setEnabled(false);
            TF_PuertoOrigen.setEnabled(false);
            TF_UsuarioOrigen.setEnabled(false);
            TF_PasswordOrigen.setEnabled(false);
        }catch(Exception e){
            e.printStackTrace();
        }    
    }//GEN-LAST:event_BT_ProbarOrigenMousePressed

    private void BT_ProbarDestinoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ProbarDestinoMousePressed
        if(!BT_ProbarDestino.isEnabled())
            return;
        String nombre = TF_NombreDestino.getText();
        String instancia = TF_IntanciaDestino.getText();
        String puerto = TF_PuertoDestino.getText();
        String usuario = TF_UsuarioDestino.getText();
        String password = TF_PasswordDestino.getText();
        Conexion conexion = new Conexion(nombre, usuario, password, instancia, puerto);
        try{
            conexion.Conectar();
            GUIReplicacion.destino = conexion;
            JOptionPane.showMessageDialog(null, "Conexion exitosa");
            BT_ProbarDestino.setEnabled(false);
            TF_IntanciaDestino.setEnabled(false);
            TF_NombreDestino.setEnabled(false);
            TF_PuertoDestino.setEnabled(false);
            TF_UsuarioDestino.setEnabled(false);
            TF_PasswordDestino.setEnabled(false);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BT_ProbarDestinoMousePressed

    private void B_GuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_GuardarMousePressed
        if(GUIReplicacion.origen == null || GUIReplicacion.destino == null){
            JOptionPane.showMessageDialog(null, "No se han establecido las conexiones");
            return;
        }
        try {
            File file = new File("./coso.bin");
            if(file.exists()){
                file.delete();
            }
            file.createNewFile();
            FileOutputStream fis = new FileOutputStream(file);
            ObjectOutputStream ois = new ObjectOutputStream(fis);
            coso origen = new coso();
            origen.basededato = GUIReplicacion.origen.basededato;
            origen.instancia = GUIReplicacion.origen.instancia;
            origen.password = GUIReplicacion.origen.password;
            origen.puerto = GUIReplicacion.origen.puerto;
            origen.usuario = GUIReplicacion.origen.usuario;
            coso destino = new coso();
            destino.basededato = GUIReplicacion.destino.basededato;
            destino.instancia = GUIReplicacion.destino.instancia;
            destino.password = GUIReplicacion.destino.password;
            destino.puerto = GUIReplicacion.destino.puerto;
            destino.usuario = GUIReplicacion.destino.usuario;
            ois.writeObject(origen);
            ois.writeObject(destino);
            ois.close();
            fis.close();
            try{
                ResultSet rs = GUIReplicacion.origen.conn.createStatement().executeQuery("SELECT * FROM link_destino");
                if(rs.next()){
                    GUIReplicacion.origen.conn.createStatement().executeQuery("DELETE FROM link_destino");
                }
                 GUIReplicacion.origen.conn.createStatement().executeQuery("INSERT INTO link_destino VALUES('Driver={SQL Server};Server="+destino.instancia+";Database="+destino.basededato+";Uid="+destino.usuario+";Pwd="+destino.password+";Encrypt=no;TrustServerCertificate=no;');");

            }catch(Exception e){
                GUIReplicacion.origen.conn.createStatement().executeQuery("CREATE TABLE link_destino (link varchar(1000))");
                GUIReplicacion.origen.conn.createStatement().executeQuery("INSERT INTO link_destino VALUES('Driver={SQL Server};Server="+destino.instancia+";Database="+destino.basededato+";Uid="+destino.usuario+";Pwd="+destino.password+";Encrypt=no;TrustServerCertificate=no;');");
            }
            try{
                ResultSet rs = GUIReplicacion.origen.conn.createStatement().executeQuery("SELECT * FROM bitacora;");
                if(rs.next()){
                    
                }
            }catch(Exception e){
                String sql = "CREATE TABLE `bitacora` (\n" +
                    "	`id_bitacora` INT(11) NOT NULL AUTO_INCREMENT,\n" +
                    "	`accion` VARCHAR(15) NOT NULL COLLATE 'latin1_swedish_ci',\n" +
                    "	`tabla` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',\n" +
                    "	`atributos` VARCHAR(200) NOT NULL COLLATE 'latin1_swedish_ci',\n" +
                    "	`olddatos` VARCHAR(200) NULL DEFAULT 'NULL' COLLATE 'latin1_swedish_ci',\n" +
                    "	`newdatos` VARCHAR(200) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',\n" +
                    "	`replicado` CHAR(1) NOT NULL COLLATE 'utf8mb3_general_ci',\n" +
                    "	PRIMARY KEY (`id_bitacora`) USING BTREE\n" +");\n";
                GUIReplicacion.origen.conn.createStatement().execute(sql);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.dispose();
        new GUIReplicacion().setVisible(true);
    }//GEN-LAST:event_B_GuardarMousePressed

   
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ProbarDestino;
    private javax.swing.JButton BT_ProbarOrigen;
    private javax.swing.JButton B_Guardar;
    private javax.swing.JPanel JPBaseDestino;
    private javax.swing.JPanel JPBaseOrigen;
    private javax.swing.JTextField TF_IntanciaDestino;
    private javax.swing.JTextField TF_IntanciaOrigen;
    private javax.swing.JTextField TF_NombreDestino;
    private javax.swing.JTextField TF_NombreOrigen;
    private javax.swing.JTextField TF_PasswordDestino;
    private javax.swing.JTextField TF_PasswordOrigen;
    private javax.swing.JTextField TF_PuertoDestino;
    private javax.swing.JTextField TF_PuertoOrigen;
    private javax.swing.JTextField TF_UsuarioDestino;
    private javax.swing.JTextField TF_UsuarioOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
